version: '3'
services:
  my-server:
    image: cardcollector:latest
    ports:
      - "8080:8080"
    env_file:
      - secrets.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.30.1.86:3306/cardcollector